name: ugr01-FA24

channels:
- conda-forge
- pytorch

dependencies:
- jupyterhub==4.1.6
- python==3.12.*
- duckdb==1.0.0
- folium==0.14.0
- gh-scoped-creds==4.1
- git==2.39.1
- h5netcdf==1.0.2
- ipywidgets==8.1.5
- jupysql==0.8.0
- jupyter-archive==3.4.0
- jupyterlab==4.2.5
- jupyterlab-favorites==3.0.0
- jupyterlab_server==2.27.3
- jupyterlab_widgets==3.0.13
- jupyter-resource-usage==1.1.0
- jupyter_server==2.14.2
- matplotlib==3.9.2
- mdit-py-plugins==0.4.2
- nbconvert==7.16.4
- nbgitpuller==1.2.1
- notebook==7.2.2
- numpy==2.1.1
- octave_kernel==0.36.0
- pandas==2.2.3
- playwright==1.47.2
- plotly==5.24.1
- pytest-notebook==0.10.0
- scikit-image==0.24.0
- scikit-learn==1.5.2
- scipy==1.14.1
- seaborn==0.13.2
- statsmodels==0.14.3
- xeus-octave==0.2.0
- pip
- pip:
  - git+https://github.com/shaneknapp/python-popularity-contest.git@add-error-handling
  - jupyter-remote-desktop-proxy==2.0.1
